### ISSUE TITLE
Unable to start jenkins using scripts

### ISSUE THREAD

**Issue by ajeetaggregatortech** [Aggregator-Tech/ci#1]
Steps to reproduce:
Clone https://github.com/Aggregator-Tech/ci.git

$ sh startJenkinsWithLatestRepo.sh 
Stopping running container aggregatortech-jenkins
Error response from daemon: No such container: aggregatortech-jenkins
Error response from daemon: No such container: aggregatortech-jenkins
Removing aggregatortech-jenkins-dv,aggregatortech-jenkins
Error response from daemon: No such container: aggregatortech-jenkins
Error response from daemon: No such container: aggregatortech-jenkins-dv
aggregatortech-jenkins-dv
volume removed successfully
Unable to find image 'jenkins/jenkins:latest' locally
latest: Pulling from jenkins/jenkins
cc1a78bfd46b: Pull complete 
6861473222a6: Pull complete 
7e0b9c3b5ae0: Pull complete 
3ec98735f56f: Pull complete 
55160131808f: Pull complete 
a8dbacf623ff: Pull complete 
8145eb5a3756: Pull complete 
e00673c707b5: Pull complete 
b21012f36779: Pull complete 
b9ba516b5689: Pull complete 
993318d97ac0: Pull complete 
890cdfa16aaf: Pull complete 
ff284454a00a: Pull complete 
16064fadee0c: Pull complete 
4f2b1138b9fb: Pull complete 
22458622d327: Pull complete 
40112f8313a3: Pull complete 
434b9b054cec: Pull complete 
a7ce6c79fd85: Pull complete 
81e5b256d784: Pull complete 
c07a50c27285: Pull complete 
Digest: sha256:24c56604682e4020f3697e910a63a5639d48ab214a18f8408cb45cc4d631210e
Status: Downloaded newer image for jenkins/jenkins:latest
0985ba937a0aa279d369ecc33e1720194d6cbab6de361b1e92f76173a99b055c
volume recreated  successfully
volume refreshed  successfully
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?

**Comment by Atul-aggregatortech** [comment]
Fixed this issue by changing the permissions
